// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "new-york": {
    "badge-theme": {
      name: "badge-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/badge-theme.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/badge-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-theme": {
      name: "card-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/card-theme.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/card-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "drawer-menu": {
      name: "drawer-menu",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/drawer-menu.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/drawer-menu.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "password-input": {
      name: "password-input",
      type: "registry:ui",
      registryDependencies: ["input","button"],
      files: ["registry/new-york/ui/password-input.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/password-input.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar": {
      name: "sidebar",
      type: "registry:ui",
      registryDependencies: ["button","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-mobile.json"],
      files: ["registry/new-york/ui/sidebar.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/sidebar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography": {
      name: "typography",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/typography.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/typography.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "hero-01": {
      name: "hero-01",
      type: "registry:block",
      registryDependencies: ["button"],
      files: ["registry/new-york/block/hero-01/page.tsx","registry/new-york/block/hero-01/components/hero-01.tsx"],
      component: React.lazy(() => import("@/registry/new-york/block/hero-01/page.tsx")),
      source: "__registry__/new-york/block/hero-01/page.tsx",
      category: "Banner",
      subcategory: "Hero",
      chunks: []
    },
    "home-page": {
      name: "home-page",
      type: "registry:block",
      registryDependencies: ["button","navigation-menu","scroll-area","sonner","toast","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/typography.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/theme-adminsys.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/next-themes.json"],
      files: ["registry/new-york/block/home-page/layout.tsx","registry/new-york/block/home-page/loading.tsx","registry/new-york/block/home-page/components/loading-spinner.tsx","registry/new-york/block/home-page/page.tsx","registry/new-york/block/home-page/about/page.tsx","registry/new-york/block/home-page/contact/page.tsx","registry/new-york/block/home-page/not-found/page.tsx","registry/new-york/block/home-page/components/not-found.tsx","registry/new-york/block/home-page/components/site-header.tsx","registry/new-york/block/home-page/components/nav-main.tsx","registry/new-york/block/home-page/components/nav-link.tsx","registry/new-york/block/home-page/components/nav-mobile.tsx","registry/new-york/block/home-page/components/site-footer.tsx","registry/new-york/block/home-page/components/site.ts"],
      component: React.lazy(() => import("@/registry/new-york/block/home-page/layout.tsx")),
      source: "__registry__/new-york/block/home-page/layout.tsx",
      category: "Web",
      subcategory: "Layout",
      chunks: []
    },
    "next-themes": {
      name: "next-themes",
      type: "registry:block",
      registryDependencies: ["button"],
      files: ["registry/new-york/block/components/provider/theme-provider.tsx","registry/new-york/block/components/layout/toggle/toggle-theme.tsx"],
      component: React.lazy(() => import("@/registry/new-york/block/components/provider/theme-provider.tsx")),
      source: "__registry__/new-york/block/components/provider/theme-provider.tsx",
      category: "Themes",
      subcategory: "Setup",
      chunks: []
    },
    "adminsys": {
      name: "adminsys",
      type: "registry:block",
      registryDependencies: ["avatar","button","dropdown-menu","scroll-area","sonner","toast","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/typography.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/theme-adminsys.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/next-themes.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/sidebar.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-mobile.json"],
      files: ["registry/new-york/block/adminsys/app/(admin)/admin/layout.tsx","registry/new-york/block/adminsys/app/(admin)/admin/loading.tsx","registry/new-york/block/adminsys/app/(admin)/admin/[...not-found]/page.tsx","registry/new-york/block/adminsys/app/(admin)/admin/dashboard/page.tsx","registry/new-york/block/adminsys/app/(admin)/admin/users/list/page.tsx","registry/new-york/block/components/auth/dropdown/dropdown-user.tsx","registry/new-york/block/components/layout/container/container.tsx","registry/new-york/block/components/layout/header/admin-header.tsx","registry/new-york/block/components/layout/loading/loading-spinner.tsx","registry/new-york/block/components/layout/logo/logo.tsx","registry/new-york/block/components/layout/not-found/not-found.tsx","registry/new-york/block/components/layout/sidebar/admin-sidebar.tsx","registry/new-york/block/components/layout/sidebar/inc/sidebar-menu-item.tsx","registry/new-york/block/components/layout/sidebar/inc/sidebar-nav-user.tsx","registry/new-york/block/adminsys/config/site.ts"],
      component: React.lazy(() => import("@/registry/new-york/block/adminsys/app/(admin)/admin/layout.tsx")),
      source: "__registry__/new-york/block/adminsys/app/(admin)/admin/layout.tsx",
      category: "Admin",
      subcategory: "Layout",
      chunks: []
    },
    "docsys": {
      name: "docsys",
      type: "registry:block",
      registryDependencies: ["button","scroll-area","sonner","toast","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/typography.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/theme-adminsys.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/next-themes.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/sidebar.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-mobile.json"],
      files: ["registry/new-york/block/docsys/app/(docs)/docs/layout.tsx","registry/new-york/block/docsys/app/(docs)/docs/loading.tsx","registry/new-york/block/docsys/app/(docs)/docs/page.tsx","registry/new-york/block/docsys/app/(docs)/docs/[...not-found]/page.tsx","registry/new-york/block/docsys/app/(docs)/docs/components/ui/badge/page.tsx","registry/new-york/block/docsys/app/(docs)/docs/components/ui/card/page.tsx","registry/new-york/block/docsys/app/(docs)/docs/components/ui/typography/page.tsx","registry/new-york/block/docsys/app/(docs)/docs/get-starter/page.tsx","registry/new-york/block/components/layout/code/code-block.tsx","registry/new-york/block/components/layout/container/container.tsx","registry/new-york/block/components/layout/header/docs-header.tsx","registry/new-york/block/components/layout/loading/loading-spinner.tsx","registry/new-york/block/components/layout/logo/logo.tsx","registry/new-york/block/components/layout/not-found/not-found.tsx","registry/new-york/block/components/layout/sidebar/docs-sidebar.tsx","registry/new-york/block/components/layout/sidebar/inc/sidebar-menu-item.tsx","registry/new-york/block/components/layout/wrapper/code-block-wrapper.tsx","registry/new-york/block/docsys/config/site.ts"],
      component: React.lazy(() => import("@/registry/new-york/block/docsys/app/(docs)/docs/layout.tsx")),
      source: "__registry__/new-york/block/docsys/app/(docs)/docs/layout.tsx",
      category: "Admin",
      subcategory: "Layout",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/new-york/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/new-york/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/new-york/hooks/use-mobile.tsx"],
      component: React.lazy(() => import("@/registry/new-york/hooks/use-mobile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },  "default": {
    "badge-theme": {
      name: "badge-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/badge-theme.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/badge-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-theme": {
      name: "card-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/card-theme.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/card-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "drawer-menu": {
      name: "drawer-menu",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/drawer-menu.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/drawer-menu.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "password-input": {
      name: "password-input",
      type: "registry:ui",
      registryDependencies: ["input","button"],
      files: ["registry/default/ui/password-input.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/password-input.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar": {
      name: "sidebar",
      type: "registry:ui",
      registryDependencies: ["button","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-mobile.json"],
      files: ["registry/default/ui/sidebar.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/sidebar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography": {
      name: "typography",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/typography.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/typography.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "hero-01": {
      name: "hero-01",
      type: "registry:block",
      registryDependencies: ["button"],
      files: ["registry/default/block/hero-01/page.tsx","registry/default/block/hero-01/components/hero-01.tsx"],
      component: React.lazy(() => import("@/registry/default/block/hero-01/page.tsx")),
      source: "__registry__/default/block/hero-01/page.tsx",
      category: "Banner",
      subcategory: "Hero",
      chunks: []
    },
    "home-page": {
      name: "home-page",
      type: "registry:block",
      registryDependencies: ["button","navigation-menu","scroll-area","sonner","toast","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/typography.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/theme-adminsys.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/next-themes.json"],
      files: ["registry/default/block/home-page/layout.tsx","registry/default/block/home-page/loading.tsx","registry/default/block/home-page/components/loading-spinner.tsx","registry/default/block/home-page/page.tsx","registry/default/block/home-page/about/page.tsx","registry/default/block/home-page/contact/page.tsx","registry/default/block/home-page/not-found/page.tsx","registry/default/block/home-page/components/not-found.tsx","registry/default/block/home-page/components/site-header.tsx","registry/default/block/home-page/components/nav-main.tsx","registry/default/block/home-page/components/nav-link.tsx","registry/default/block/home-page/components/nav-mobile.tsx","registry/default/block/home-page/components/site-footer.tsx","registry/default/block/home-page/components/site.ts"],
      component: React.lazy(() => import("@/registry/default/block/home-page/layout.tsx")),
      source: "__registry__/default/block/home-page/layout.tsx",
      category: "Web",
      subcategory: "Layout",
      chunks: []
    },
    "next-themes": {
      name: "next-themes",
      type: "registry:block",
      registryDependencies: ["button"],
      files: ["registry/default/block/components/provider/theme-provider.tsx","registry/default/block/components/layout/toggle/toggle-theme.tsx"],
      component: React.lazy(() => import("@/registry/default/block/components/provider/theme-provider.tsx")),
      source: "__registry__/default/block/components/provider/theme-provider.tsx",
      category: "Themes",
      subcategory: "Setup",
      chunks: []
    },
    "adminsys": {
      name: "adminsys",
      type: "registry:block",
      registryDependencies: ["avatar","button","dropdown-menu","scroll-area","sonner","toast","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/typography.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/theme-adminsys.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/next-themes.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/sidebar.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-mobile.json"],
      files: ["registry/default/block/adminsys/app/(admin)/admin/layout.tsx","registry/default/block/adminsys/app/(admin)/admin/loading.tsx","registry/default/block/adminsys/app/(admin)/admin/[...not-found]/page.tsx","registry/default/block/adminsys/app/(admin)/admin/dashboard/page.tsx","registry/default/block/adminsys/app/(admin)/admin/users/list/page.tsx","registry/default/block/components/auth/dropdown/dropdown-user.tsx","registry/default/block/components/layout/container/container.tsx","registry/default/block/components/layout/header/admin-header.tsx","registry/default/block/components/layout/loading/loading-spinner.tsx","registry/default/block/components/layout/logo/logo.tsx","registry/default/block/components/layout/not-found/not-found.tsx","registry/default/block/components/layout/sidebar/admin-sidebar.tsx","registry/default/block/components/layout/sidebar/inc/sidebar-menu-item.tsx","registry/default/block/components/layout/sidebar/inc/sidebar-nav-user.tsx","registry/default/block/adminsys/config/site.ts"],
      component: React.lazy(() => import("@/registry/default/block/adminsys/app/(admin)/admin/layout.tsx")),
      source: "__registry__/default/block/adminsys/app/(admin)/admin/layout.tsx",
      category: "Admin",
      subcategory: "Layout",
      chunks: []
    },
    "docsys": {
      name: "docsys",
      type: "registry:block",
      registryDependencies: ["button","scroll-area","sonner","toast","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/typography.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/theme-adminsys.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/next-themes.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/sidebar.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-mobile.json"],
      files: ["registry/default/block/docsys/app/(docs)/docs/layout.tsx","registry/default/block/docsys/app/(docs)/docs/loading.tsx","registry/default/block/docsys/app/(docs)/docs/page.tsx","registry/default/block/docsys/app/(docs)/docs/[...not-found]/page.tsx","registry/default/block/docsys/app/(docs)/docs/components/ui/badge/page.tsx","registry/default/block/docsys/app/(docs)/docs/components/ui/card/page.tsx","registry/default/block/docsys/app/(docs)/docs/components/ui/typography/page.tsx","registry/default/block/docsys/app/(docs)/docs/get-starter/page.tsx","registry/default/block/components/layout/code/code-block.tsx","registry/default/block/components/layout/container/container.tsx","registry/default/block/components/layout/header/docs-header.tsx","registry/default/block/components/layout/loading/loading-spinner.tsx","registry/default/block/components/layout/logo/logo.tsx","registry/default/block/components/layout/not-found/not-found.tsx","registry/default/block/components/layout/sidebar/docs-sidebar.tsx","registry/default/block/components/layout/sidebar/inc/sidebar-menu-item.tsx","registry/default/block/components/layout/wrapper/code-block-wrapper.tsx","registry/default/block/docsys/config/site.ts"],
      component: React.lazy(() => import("@/registry/default/block/docsys/app/(docs)/docs/layout.tsx")),
      source: "__registry__/default/block/docsys/app/(docs)/docs/layout.tsx",
      category: "Admin",
      subcategory: "Layout",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-mobile.tsx"],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
