// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "new-york": {
    "card-user-profile": {
      name: "card-user-profile",
      type: "registry:component",
      registryDependencies: ["avatar","card"],
      files: ["registry/new-york/ui/components/auth/card/card-user-profile.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/components/auth/card/card-user-profile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "badge-theme": {
      name: "badge-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/badge-theme.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/badge-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "banner": {
      name: "banner",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/banner.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/banner.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-theme": {
      name: "button-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/button-theme.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/button-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-theme": {
      name: "card-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/card-theme.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/card-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "drawer-menu": {
      name: "drawer-menu",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/drawer-menu.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/drawer-menu.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "password-input": {
      name: "password-input",
      type: "registry:ui",
      registryDependencies: ["input","button"],
      files: ["registry/new-york/ui/password-input.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/password-input.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar": {
      name: "sidebar",
      type: "registry:ui",
      registryDependencies: ["button","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-mobile.json"],
      files: ["registry/new-york/ui/sidebar.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/sidebar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toast-theme": {
      name: "toast-theme",
      type: "registry:ui",
      registryDependencies: ["https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-toast-theme.json"],
      files: ["registry/new-york/ui/toast-theme.tsx","registry/new-york/ui/toaster-theme.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/toast-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography": {
      name: "typography",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/new-york/ui/typography.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/typography.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "components-auth": {
      name: "components-auth",
      type: "registry:component",
      registryDependencies: ["avatar","card"],
      files: ["registry/new-york/block/components/auth/card/card-user-profile.tsx","registry/new-york/block/components/auth/dropdown/dropdown-user.tsx","registry/new-york/block/components/auth/form/account-form.tsx","registry/new-york/block/components/auth/form/forgot-password-form.tsx","registry/new-york/block/components/auth/form/form-auth.tsx","registry/new-york/block/components/auth/form/new-verification-form.tsx","registry/new-york/block/components/auth/form/reset-password-form.tsx","registry/new-york/block/components/auth/form/sign-in-form.tsx","registry/new-york/block/components/auth/form/sign-up-form.tsx","registry/new-york/block/components/auth/form/social-login.tsx","registry/new-york/block/components/auth/sidebar/sidebar-settings.tsx","registry/new-york/block/components/auth/wrapper/card-auth-wrapper.tsx"],
      component: React.lazy(() => import("@/registry/new-york/block/components/auth/card/card-user-profile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/new-york/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/new-york/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/new-york/hooks/use-mobile.tsx"],
      component: React.lazy(() => import("@/registry/new-york/hooks/use-mobile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-toast-theme": {
      name: "use-toast-theme",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/new-york/hooks/use-toast-theme.ts"],
      component: React.lazy(() => import("@/registry/new-york/hooks/use-toast-theme.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },  "default": {
    "card-user-profile": {
      name: "card-user-profile",
      type: "registry:component",
      registryDependencies: ["avatar","card"],
      files: ["registry/default/ui/components/auth/card/card-user-profile.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/components/auth/card/card-user-profile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "badge-theme": {
      name: "badge-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/badge-theme.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/badge-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "banner": {
      name: "banner",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/banner.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/banner.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-theme": {
      name: "button-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/button-theme.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/button-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-theme": {
      name: "card-theme",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/card-theme.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/card-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "drawer-menu": {
      name: "drawer-menu",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/drawer-menu.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/drawer-menu.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "password-input": {
      name: "password-input",
      type: "registry:ui",
      registryDependencies: ["input","button"],
      files: ["registry/default/ui/password-input.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/password-input.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar": {
      name: "sidebar",
      type: "registry:ui",
      registryDependencies: ["button","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/drawer-menu.json","https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-mobile.json"],
      files: ["registry/default/ui/sidebar.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/sidebar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toast-theme": {
      name: "toast-theme",
      type: "registry:ui",
      registryDependencies: ["https://raw.githubusercontent.com/MaskSysDev/adminsys-components/refs/heads/main/public/r/styles/default/use-toast-theme.json"],
      files: ["registry/default/ui/toast-theme.tsx","registry/default/ui/toaster-theme.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/toast-theme.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography": {
      name: "typography",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/typography.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/typography.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "components-auth": {
      name: "components-auth",
      type: "registry:component",
      registryDependencies: ["avatar","card"],
      files: ["registry/default/block/components/auth/card/card-user-profile.tsx","registry/default/block/components/auth/dropdown/dropdown-user.tsx","registry/default/block/components/auth/form/account-form.tsx","registry/default/block/components/auth/form/forgot-password-form.tsx","registry/default/block/components/auth/form/form-auth.tsx","registry/default/block/components/auth/form/new-verification-form.tsx","registry/default/block/components/auth/form/reset-password-form.tsx","registry/default/block/components/auth/form/sign-in-form.tsx","registry/default/block/components/auth/form/sign-up-form.tsx","registry/default/block/components/auth/form/social-login.tsx","registry/default/block/components/auth/sidebar/sidebar-settings.tsx","registry/default/block/components/auth/wrapper/card-auth-wrapper.tsx"],
      component: React.lazy(() => import("@/registry/default/block/components/auth/card/card-user-profile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-mobile.tsx"],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-toast-theme": {
      name: "use-toast-theme",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-toast-theme.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-toast-theme.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
